### ISSUE TITLE
Github Actions For MTTR and Change Failure Rate not present

### ISSUE THREAD

**Issue by shubham-elanco** [DeveloperMetrics/DevOpsMetrics#1034]
Want to understand that are github actions available for MTTR and Change Failure Rate?

**Comment by samsmithnz** [comment]
@shubham-elanco  They aren't present because these are much more difficult to measure with Actions - where as the first two are related to CI, and hence a little easier to capture.
- MTTR: Relies on understanding where the service was deployed and what is a failure. Is the application a database? A web service? a container hosting a web service? There are so many variables there, it's up to the user to decide what is a failure/degradation and how to measure it - that is why this DevOpsMetrics project taps into Azure Alerts - letting the application owner decide what a failure is.
- Change Failure Rate: Similar - in that it's up to the application owner to say what a failure is - and I believe in general this is the hardest one to automate. It's easy to say that after a new application deployment, if the website doesn't load - that is a change failure. But what if you deploy a change that doesn't fail for a week? How do you know that deployment was the issue? This also depends on where the application was deployed.
